import type { DiffResult } from "./types";
import c02 from "./history/c02.json";
import c03 from "./history/c03.json";
import c04 from "./history/c04.json";
import c05 from "./history/c05.json";
import c06 from "./history/c06.json";
import c07 from "./history/c07.json";

// Pre-generated DiffResults for each commit in the c01→c07 chain — real engine
// output (argus-diff on each consecutive pair, regenerated by `make fixtures`),
// bundled so the History rail works entirely in the browser. c01 is the base
// (nothing before it → null). Each cNN is the diff of atlas_c(NN-1)→atlas_cNN,
// so values are continuous across the chain.
//
// THE ENGINE INTEGRATION POINT: in the Wails app, swap the bundled lookup for a
// live `window.go.main.App.Diff(parentPath, path)` call resolved from the
// commit's file pair. Nothing else in the UI changes (identical DiffResult).
// Validate bundled JSON against the contract at load, instead of an unchecked
// `as unknown as DiffResult`. If the engine's output shape ever drifts, this
// throws loudly at startup rather than surfacing as `undefined` mid-render.
function asDiff(x: unknown, id: string): DiffResult {
  const d = x as DiffResult;
  if (
    !d ||
    d.schemaVersion !== 1 ||
    !Array.isArray(d.sheets) ||
    !Array.isArray(d.cascades) ||
    !Array.isArray(d.anomalies) ||
    typeof d.summary?.authoredCount !== "number"
  ) {
    throw new Error(`bundled diff ${id} is not a valid DiffResult`);
  }
  // Anomaly detection is disabled for the demo: the magnitude heuristic flags
  // legitimate input-driven cascades (e.g. capex doubles → PP&E moves 60%+) as
  // "anomalies", which reads as a false alarm on a correct change. The cascade +
  // blast-radius already show exactly what moved, so reviewers can judge the
  // numbers themselves. Engine still computes anomalies (kept + tested); we drop
  // them at ingestion. To re-enable, delete this line. See also store.ts.
  return { ...d, anomalies: [] };
}

const DIFFS: Record<string, DiffResult> = {
  c02: asDiff(c02, "c02"),
  c03: asDiff(c03, "c03"),
  c04: asDiff(c04, "c04"),
  c05: asDiff(c05, "c05"),
  c06: asDiff(c06, "c06"),
  c07: asDiff(c07, "c07"),
};

/**
 * The diff a commit introduced (vs. its parent). Returns null for the base
 * commit c01 (nothing before it).
 */
export function diffForCommit(id: string): DiffResult | null {
  return DIFFS[id] ?? null;
}
