// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Diff(arg1, arg2) {
  return window['go']['main']['App']['Diff'](arg1, arg2);
}
